### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by kwent** [quip/quip-api#11]
Hello,

Search API does not officially exist at https://quip.com/api/reference

Would be nice if you could open an endpoint to perform searches like `/search?query=xxxx` and return a list of documents with their associated id as the website does.

Regards,

**Comment by kidpollo** [comment]
Any comments on this ?

**Comment by shkfnly** [comment]
Can we get information about this?

**Comment by orf** [comment]
This is a major missing feature with the API!

**Comment by luizhcrocha** [comment]
I follow

**Comment by FelixLou** [comment]
+1, cannot believe we don't have this feature...

**Comment by willhite** [comment]
https://corp.quip.com/dev/automation/documentation#search-for-threads
