### ISSUE TITLE
Bug in the `baqup` script

### ISSUE THREAD

**Issue by z-jason** [quip/quip-api#18]
When I run the script, this following line throws an exception.

```
title = folder["folder"]["title"]
```

I found that the reason is the `folder["folder"]` does not have key "title"

**Comment by mihaip** [comment]
Thanks for noticing this. The problem was that the "Starred" folder did not have a title when output by the API. I've made the script more resilient to this, and I've also done a server-side fix to make sure that the folder does get a title.
