### ISSUE TITLE
Can I get the document share link use quip-api?

### ISSUE THREAD

**Issue by liaoxiaorong** [quip/quip-api#2]
I cant share a document  and got the document share link use quip-api.
Are you planning to add this.

**Comment by caseymrm** [comment]
Hi @liaoxiaorong - the share link is now returned in the thread's json as ```thread["thread"]["link"]```

It will be added to the documentation shortly. Thanks again for the report.

**Comment by liaoxiaorong** [comment]
Quip is amazing, I'm really enjoy using it. Thanks for your work.

**Comment by amn41** [comment]
Hi - is this still supported? I can't see anything about creating sharing links in the QUIP api reference

**Comment by kevgibbs** [comment]
Hey there. The functionality is supported. Currently, however, we only return the document sharing link over the API. We don't yet allow you to create a sharing link via the API. (That must be done in product.)

Would you like to be able to create sharing links via the API for documents? If so, what kind of sharing permissions do you want for your use case?

**Comment by amn41** [comment]
Yes, I would definitely like to be able to create sharing links over the API. The basic use case would be to create a public read-only link. But of course it would be useful to programatically control permissions as well. Would love the chance to chat about our plans with the API if you shoot me a mail (address in img)
![screen shot 2015-07-15 at 08 26 47](https://cloud.githubusercontent.com/assets/5114084/8692115/444f6020-2acb-11e5-8460-d42f6ae07684.png)

**Comment by john-brock** [comment]
Follow-up -- here are the API docs for this feature. https://quip.com/dev/automation/documentation/current#operation/editThreadLinkShareSettings
