### ISSUE TITLE
demo code in python api fails

### ISSUE THREAD

**Issue by dangoldner** [quip/quip-api#41]
In commit 12254a4c201, line 394 of quip.py replaces semicolons with underscores in the section_id, but this fails when no section_id is specified (as in the demo example) because by default, `section_id=None`. 
![screen shot 2018-07-29 at 5 18 33 pm](https://user-images.githubusercontent.com/26610553/43371380-184b69f0-9356-11e8-8fee-970126c62134.png)

**Comment by willhite** [comment]
Thanks for pointing this out.
