### ISSUE TITLE
python client.edit_document failing with any operation requiring section_id

### ISSUE THREAD

**Issue by mkj28** [quip/quip-api#46]
For html:
```
u"<h1 id='MZNACACqNMj'>Test</h1>\n\n<p id='MZNACAJjo49' class='line'>test</p>\n\n<p id='MZNACAevQlK' class='line'>\u200b</p>\n\n"
```

`client.edit_document(quip_document, '<p>new text</p>', operation=4, section_id=`MZNACAJjo49`)`

is failing with:
`quip.QuipError: 400: This document does not support updates with the given location type and section_id.`

same with any other operation that requires section_id

**Comment by belindagu** [comment]
Thanks for the report! Fixing, should be live tomorrow.

**Comment by mkj28** [comment]
thanks, is the fix on the server side or python client code?

**Comment by belindagu** [comment]
Fix is on the server.

**Comment by mkj28** [comment]
Still seeing the same. Is the fix out @belindagu ?

**Comment by belindagu** [comment]
No, sorry, it won't be live until tomorrow around 3-4pm. Apologies for the delay.

**Comment by akskha** [comment]
I am still running into this issue. 

```
args::  {'thread_id': 'bfN9AArOUJ5', 'content': '<p>W6</p>', 'location': 4, 'format': 'html', 'section_id': 'bfN9CA9AWRO'}
request::  b'thread_id=bfN9AArOUJ5&content=%3Cp%3EW6%3C%2Fp%3E&location=4&format=html&section_id=bfN9CA9AWRO'
```
is failing with:
```
quip.QuipError: 400: This document does not support updates with the given location type and section_id.
```
