### ISSUE TITLE
Is it possible to see the list of changes made to a thread with the corresponding author?

### ISSUE THREAD

**Issue by dclaze** [quip/quip-api#77]
I am looking to get notifications of changes to a document, similar to the 'Conversation' section of a given document where I see '**Example User** made edits' and then I see a list of changes made by that user.

![example-screenshot](https://i.ibb.co/YcXhF8H/Screen-Shot-2020-10-18-at-10-29-32-AM.png)

**Comment by dclaze** [comment]
Answering my own question ....

I discovered the `message_type` parameter of the [Get Recent Messages](https://quip.com/dev/automation/documentation#get-recent-messages) API. When set to `message_type=edit` returns a diff of the changes. 

See related update #78

**Comment by jesseditson** [comment]
Seems like #78 fixes this, closing it out.
